### ISSUE TITLE
No testhacc_io

### ISSUE THREAD

**Issue by HenryYihengXu** [glennklockwood/hacc-io#2]
Hello! I followed the instruction to install it. But it didn't generate an executable called testhacc_io. Instead, it generated an executable called hacc_io. I'm assuming that's the correct one I should use right? Thanks!

**Comment by glennklockwood** [comment]
That's right; `hacc_io` is the correct binary.  If you look in the makefile, you can build a read-only and write-only version too, called `hacc_io_write` and `hacc_io_read`.
